### ISSUE TITLE
mlir的一点疑问

### ISSUE THREAD

**Issue by zouxz** [sophgo/tpu-mlir#10]
请教一下作者大佬：
1、目前来看基于mlir做编译栈的最主要因素是什么呢？这种dsa架构是否用tvm这种端到端的编译器开发起来要快一点？
2、mlir的愿景是提供一个编译器生态，就算各家厂商通过dialect把自己硬件相关的ir优化接入mlir，并且开源，但是别人也很难用上啊，毕竟用的不是同一个硬件后端。那这样各家都自己搞一套优化然后再接入dialect，感觉这样反而冗余了。

**Comment by HarmonyHu** [comment]
你好。
1. 基于MLIR做编译器，主要是借助它成熟架构和分层设计。哪一种更快不好说。
2. MLIR的愿景和LLVM的是一样的，它试图通过分层IR，把不同的前端编译到不同的后端。因为这本身就是个非常复杂的工程，所以感觉难用是很正常的。MLIR目前朝着这个愿景在探索，个人觉得它还是提供了很大的便利。

**Comment by HarmonyHu** [comment]
close
