### ISSUE TITLE
mlir不支持yoloer模型转换

### ISSUE THREAD

**Issue by XiaBing992** [sophgo/tpu-mlir#117]
error: imeError: Op not support:{'Cos', 'Sin'}
转换报错这两个算子不支持，有什么解决方法吗

**Comment by charlesxzb** [comment]
你好，请问你现在是转的caffe模型吗？Cos和Sin算子在后端都是已经支持的，[caffe](https://github.com/sophgo/tpu-mlir/blob/master/python/transform/CaffeConverter.py)这里前端还没补充，在后续的版本我们会补上，或者你也可以尝试参照其它算子的convert函数添加上
