### ISSUE TITLE
1684详细的转换流程

### ISSUE THREAD

**Issue by ijiami-01** [sophgo/tpu-mlir#124]
如题，我在model_deploy.py将chip从1684x改1684，发现转换报错，失败。
阅读过 https://github.com/sophgo/tpu-mlir/issues/102 ，但是说的不是很清晰。
以下是我的报错上下文。
>   /workspace/model_yolov5s/workspace# model_deploy.py \
>   --mlir yolov5s.mlir \
>   --quantize F16 \
>   --chip bm1684 \
>   --test_input yolov5s_in_f32.npz \
>   --test_reference yolov5s_top_outputs.npz \
>   --model yolov5s_1684x_f16.bmodel
SOPHGO Toolchain v1.2.beta.0-20230705
[Running]: tpuc-opt yolov5s.mlir --chip-assign="chip=bm1684" --chip-top-optimize --convert-top-to-tpu="mode=F16  asymmetric=False" --canonicalize -o yolov5s_bm1684_f16_tpu.mlir 
Not Implemented
UNREACHABLE executed at ../include/tpu_mlir/Conversion/TopToTpu/TopLowering.h:172!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.

**Comment by sdu-gyf** [comment]
1684不支持f16,只支持f32和int8
