### ISSUE TITLE
how the function `eraseForward` working?

### ISSUE THREAD

**Issue by lordrebel** [sophgo/tpu-mlir#159]
the definition is here:
https://github.com/sophgo/tpu-mlir/blob/882a3523221481145f7114c215cc1267920a3637/lib/Dialect/Tpu/Transforms/Distribute.cpp#L219

it looks like a useless fuction, could you help me to understand the1 meaning of this function ?

**Comment by HarmonyHu** [comment]
Thank you. these codes are not finished. it should erase op if op has no use. @lordrebel
