### ISSUE TITLE
关于layer group的疑问

### ISSUE THREAD

**Issue by sunnycase** [sophgo/tpu-mlir#16]
看到您在其他回答里提到SRAM比较小，但是从源码中也看到目前的layer group策略只在NH切，不切C，weights也不重复load，这样能fuse的层数不是很有限吗，对DDR的带宽需求会增加吧？

**Comment by HarmonyHu** [comment]
你好。一般weight会比较小，比如输入[8, 16, 320, 320]，filter shape为[32, 16, 3,3]，输出shape为[8, 32, 320, 320]。从这里可以看出主要需要的memory是输入和输出，weights其实是比较小的。所以只要把输入和输出的h和n做切分就可以做到用较小的sram跑大的网络

**Comment by sunnycase** [comment]
感谢回答，一般CNN前面的层fmap会比较大，weights比较小。但是后面的层channel数会到1024/4096之类的数，weights会变得很大，这些层你们是不做fuse吗？

**Comment by ColdCodeCool** [comment]
> 感谢回答，一般CNN前面的层fmap会比较大，weights比较小。但是后面的层channel数会到1024/4096之类的数，weights会变得很大，这些层你们是不做fuse吗？

猜测weight较大时应该是会切weight吧，一次少算一些output？

**Comment by sunnycase** [comment]
> > 感谢回答，一般CNN前面的层fmap会比较大，weights比较小。但是后面的层channel数会到1024/4096之类的数，weights会变得很大，这些层你们是不做fuse吗？
> 
> 猜测weight较大时应该是会切weight吧，一次少算一些output？

单层算子里有切C的，layer group里没看到

**Comment by HarmonyHu** [comment]
> > > 感谢回答，一般CNN前面的层fmap会比较大，weights比较小。但是后面的层channel数会到1024/4096之类的数，weights会变得很大，这些层你们是不做fuse吗？
> > 
> > 
> > 猜测weight较大时应该是会切weight吧，一次少算一些output？
> 
> 单层算子里有切C的，layer group里没看到

目前还没有去切C，后面再改进。一般会优先切OC。
