### ISSUE TITLE
cvimodel检测出错

### ISSUE THREAD

**Issue by sanzhang3** [sophgo/tpu-mlir#181]
在将yolov5s.onnx转换为f16精度之后，运行detect时报错。
root@2c84df3bc13a:/workspace/yolov5/yolov5s_onnx/workspace# detect_yolov5.py \
> --input ../image/dog.jpg \
> --model yolov5s_cv181x_f16.cvimodel \
> --output dog_f16.jpg
setenv:cv181x
Start TPU Simulator for cv181x
device[0] opened, 4294967296
version: 1.4.0
yolov5s Build at 2024-07-29 14:46:27 For platform cv181x
Cmodel: bm_load_cmdbuf
Max SharedMem size:13107200
Cmodel: bm_run_cmdbuf
device[0] closed
Traceback (most recent call last):
  File "/workspace/yolov5/tpu-mlir/python/samples/detect_yolov5.py", line 365, in <module>
    main()
  File "/workspace/yolov5/tpu-mlir/python/samples/detect_yolov5.py", line 341, in main
    scores, boxes_xyxy = postproc(output, input_shape, top, left)
  File "/workspace/yolov5/tpu-mlir/python/samples/detect_yolov5.py", line 285, in postproc
    pred = np.concatenate(z, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by fadiaburaid** [comment]
@sanzhang3 Did you find a solution for the error? I am getting the same error.

**Comment by sanzhang3** [comment]
> @sanzhang3 Did you find a solution for the error? I am getting the same error.

Yes，you can try add args --fused_preprocess --quant_input when you run the model_deploy.py. Read TPU-MLIR_Technical_Reference_Manual.pdf 3.2.4 for detail.

**Comment by fadiaburaid** [comment]
@sanzhang3 Thank you. I will give it  a try.

**Comment by HarmonyHu** [comment]
cv181x not support f16, but support bf16 and int8. you can test it by: 
``` shell
cd /workspace/tpu-mlir/regression/
./run_model.py yolov5s --chip cv181x --mode int8_sym
```
