### ISSUE TITLE
the meaning of traits: ShapeProducer, ShapeConsumer

### ISSUE THREAD

**Issue by PPG11** [sophgo/tpu-mlir#196]
excuse me, 
there are 2 traits: `ShapeProducer`, `ShapeConsumer`, and it seems like the 2 treats are used in Lowering phase, could you tell me the different between them, and what is the meaning of the 2 treats?
thanks

**Comment by HarmonyHu** [comment]
ShapeProducer is a trait for op that will output shape tensor, ShapeOp as example.
ShapeProducer means that op will use Shape tensor as input, ConstantFillOp as example.
These shape related traits use to support dynamic shape situation.

**Comment by PPG11** [comment]
get it, thank you very much
