### ISSUE TITLE
请问什么时候GMem和codegen的文档会出来？

### ISSUE THREAD

**Issue by ColdCodeCool** [sophgo/tpu-mlir#23]
各位作者辛苦了

**Comment by HarmonyHu** [comment]
GMem是关于Global Mem（也就是片外内存）是如何高效分配的，近期会出来。
Codegen是关于tpu层算子如何转换成tpu的指令集的，这部分内容涉及到具体的芯片架构，比较晦涩，不太好写，可能要到明年出来。

**Comment by ColdCodeCool** [comment]
> GMem是关于Global Mem（也就是片外内存）是如何高效分配的，近期会出来。 Codegen是关于tpu层算子如何转换成tpu的指令集的，这部分内容涉及到具体的芯片架构，比较晦涩，不太好写，可能要到明年出来。

请问Local mem的分配，您之前提到你们的芯片也是多级cache，请问多级cache又是怎么分配的呢

**Comment by HarmonyHu** [comment]
这个跟芯片有很大关系，不好描述。简单来说就是Global Memory放的是完全的数据，切片后放到Local Mem做计算。比如卷积可以切OC，或切H，或切W。
