### ISSUE TITLE
How to debug tpu-mlir?

### ISSUE THREAD

**Issue by ColdCodeCool** [sophgo/tpu-mlir#24]

**Comment by HarmonyHu** [comment]
Hi 调试方法有这么几种：
1 网络调试，在regression目录添加模型的配置，参考现有网络，然后./run_model.sh xxx执行它
2 算子调试，在test_onnx.py文件里面添加某个算子的测试用例，然后执行test_onnx.py xxxx执行它
3 model_runner调试，使用gdb --args python /workspace/tpu-mlir/python/tools/model_runner.py --input resnet18_in_f32.npz --model resnet18_opt.mlir --output resnet18_out.npz
4 其他代码单步跟踪调试，python使用pdb.set_trace()，c++用gdb --args

**Comment by ColdCodeCool** [comment]
> Hi 调试方法有这么几种： 1 网络调试，在regression目录添加模型的配置，参考现有网络，然后./run_model.sh xxx执行它 2 算子调试，在test_onnx.py文件里面添加某个算子的测试用例，然后执行test_onnx.py xxxx执行它 3 model_runner调试，使用gdb --args python /workspace/tpu-mlir/python/tools/model_runner.py --input resnet18_in_f32.npz --model resnet18_opt.mlir --output resnet18_out.npz 4 其他代码单步跟踪调试，python使用pdb.set_trace()，c++用gdb --args

多谢，请问调试python和c++混合程序，想看到c++的调用如何进行呢

**Comment by HarmonyHu** [comment]
gdb --args python /workspace/tpu-mlir/python/tools/model_runner.py --input resnet18_in_f32.npz --model resnet18_opt.mlir --output resnet18_out.npz
这个就是的，可以参考这个样gdb

**Comment by HarmonyHu** [comment]
![image](https://user-images.githubusercontent.com/10864766/194821812-1e101610-2839-42d9-b97e-bbb19c9cee2f.png)
我们有个微信群，可以群里一起学习交流
