### ISSUE TITLE
soft-pipeline

### ISSUE THREAD

**Issue by qiuliang1993** [sophgo/tpu-mlir#48]
` //==============================
  // stage assignment
  //==============================
  // 3-stage software pipeline default
  int stage_num = 3;
  // layers are assigned to stage 1 default
  for (uint32_t i = 0; i < timestep_table.size(); ++i) {
    const GdmaTsField &tensors = timestep_table[i].gdma0_ts_field;
    for (uint32_t j = 0; j < tensors.size(); ++j) {
      if (i == 0) {
        // assign stage 0 for tensors in the first timestep
        tensor_swpipl_stage.insert(std::make_pair(tensors[j], 0));
      } else if (i == timestep_table.size() - 1) {
        // assign stage 2 for tensors in the last timestep
        tensor_swpipl_stage.insert(std::make_pair(tensors[j], 2));
      } else {
        // assign stage 1 for other tensors
        tensor_swpipl_stage.insert(std::make_pair(tensors[j], 1));
      }
    }
  }`

1. 为什么这里的stage为3？
2. 如果按照2级存储3级流水理解，那为什么会把load模型参数的tensor标记为1？

**Comment by HarmonyHu** [comment]
<img width="913" alt="image" src="https://user-images.githubusercontent.com/10864766/200454249-d0f4b3e2-d391-4102-8adf-f940b392a530.png">
stage在代码是这样的概念，DDR到LMEM是load，LMEM到DDR是store，中间是compute。load/store 与 compute是可以并行的：compute的同时可以load下一个op需要的权重或输入。

**Comment by qiuliang1993** [comment]
好的，非常感谢
我再请教一个问题，我之前一直认为在分配timestep过程中，一个compute operation占用一个时间戳，但是我从coding中发现，当两个相邻的compute operation且第二个compute operation不需要模型参数时，是把这两个compute operation分配在同一个时间戳，对于这个操作，我有点不太理解

**Comment by qiuliang1993** [comment]
> <img alt="image" width="913" src="https://user-images.githubusercontent.com/10864766/200454249-d0f4b3e2-d391-4102-8adf-f940b392a530.png">
> 
> stage在代码是这样的概念，DDR到LMEM是load，LMEM到DDR是store，中间是compute。load/store 与 compute是可以并行的：compute的同时可以load下一个op需要的权重或输入。

好的，非常感谢，明白了
我再请教一个问题，我之前一直认为在分配timestep过程中，一个compute operation占用一个时间戳，但是我从coding中发现，当两个相邻的compute operation且第二个compute operation不需要模型参数时，是把这两个compute operation分配在同一个时间戳，对于这个操作，我有点不太理解

**Comment by HarmonyHu** [comment]
> > <img alt="image" width="913" src="https://user-images.githubusercontent.com/10864766/200454249-d0f4b3e2-d391-4102-8adf-f940b392a530.png">
> > stage在代码是这样的概念，DDR到LMEM是load，LMEM到DDR是store，中间是compute。load/store 与 compute是可以并行的：compute的同时可以load下一个op需要的权重或输入。
> 
> 好的，非常感谢，明白了 我再请教一个问题，我之前一直认为在分配timestep过程中，一个compute operation占用一个时间戳，但是我从coding中发现，当两个相邻的compute operation且第二个compute operation不需要模型参数时，是把这两个compute operation分配在同一个时间戳，对于这个操作，我有点不太理解

确实是这样的，这个还是与芯片架构有关。原因是compute操作和compute操作只能串行，所以当他们连在一起时，算一个timestep。这样它可以插入一个更大的load或者store操作去并行。

**Comment by ColdCodeCool** [comment]
> 

大佬，我不理解，既然compute和compute只能串行，然后他们连在一起时，反而算一个time step，不应该是两个吗

**Comment by ColdCodeCool** [comment]
> > > <img alt="image" width="913" src="https://user-images.githubusercontent.com/10864766/200454249-d0f4b3e2-d391-4102-8adf-f940b392a530.png">
> > > stage在代码是这样的概念，DDR到LMEM是load，LMEM到DDR是store，中间是compute。load/store 与 compute是可以并行的：compute的同时可以load下一个op需要的权重或输入。
> > 
> > 
> > 好的，非常感谢，明白了 我再请教一个问题，我之前一直认为在分配timestep过程中，一个compute operation占用一个时间戳，但是我从coding中发现，当两个相邻的compute operation且第二个compute operation不需要模型参数时，是把这两个compute operation分配在同一个时间戳，对于这个操作，我有点不太理解
> 
> 确实是这样的，这个还是与芯片架构有关。原因是compute操作和compute操作只能串行，所以当他们连在一起时，算一个timestep。这样它可以插入一个更大的load或者store操作去并行。

@qiuliang1993 朋友，你理解这句话的意思吗

**Comment by qiuliang1993** [comment]
举个例子，如果是conv+ relu算子，如果硬件架构支持，可以看成是一个compute算子，就能对的上大佬的解释了
