### ISSUE TITLE
Some Questions about LayerGroup

### ISSUE THREAD

**Issue by smallccn** [sophgo/tpu-mlir#62]
Dear sir,

I've saw the doc and source code for LayerGroup, but there is one thing makes me confuesed.

About the function of `isLgSupport`, it seems to find the start and end for a group.
My question is that how it confirm a start idx and end idx in a network.

For example, about the demo model yolov5s.onnx, when try to find the first group, the start(134) and end(145) are awlays same, envn I change the chip memroy size.

```C++
while (end_idx >= 0) {
    if (isLgSupport(end_idx) == true) {
      break;
    }
    end_idx--;
  }
  start_idx = end_idx;
  while (start_idx > 0) {
    if (isLgSupport(start_idx - 1) == false) {
      break;
    }
    start_idx--;
  }
```

**Comment by HarmonyHu** [comment]
isLgSupport is just an interface to check operation support calc in local mem. For example, Pool2DOp::LocalGenSupport(), we only support stride <= 15, or will only support global codegen.

start 134 end 145 always the same, is because they can group together by different slice.
