### ISSUE TITLE
工具链的两点疑问

### ISSUE THREAD

**Issue by chenhaoc** [sophgo/tpu-mlir#7]
我试用了一下工具链，有两个问题请教一下：
1. 在tpuc-opt 生成bmodel的过程中，会输出一个compiler_profile_0.txt，里面有对每一层算子的时间估计，想问一下这个时间估计是如何得到的？和真实芯片跑出来的结果会有差异吗？为什么不是在运行cmodel的时候输出这种性能信息呢？
2. model_runner.py 在运行bmodel的时候看起来是会调用cmodel 来执行？运行时间很长是否会优化？

**Comment by HarmonyHu** [comment]
hi 你好。
第一个问题：每个算子的运算量、需要多少cycle，是可以在模型编译阶段就可以算出来的，由此可以估算出时间。它和真实芯片的时间误差在20%以内。cmodel也可以输出该信息。
第二个问题：跑bmodel确实是用cmodel来执行，为了模型真实的芯片指令，时间确实会比较长。可能不太好优化，可以执行mlir替代，model_runner.py --input xxx.npz --model xxx_tpu.mlir --output output.npz，它与bmodel执行结果一致，这个会执行的很快，因为它只模型算子运算，不模拟芯片指令。

**Comment by chenhaoc** [comment]
谢谢解答！

**Comment by ColdCodeCool** [comment]
很前沿，很有借鉴意义的工作，感谢开源！
