### ISSUE TITLE
Can TPU-MLIR be run outside of docker?

### ISSUE THREAD

**Issue by WoongQ** [sophgo/tpu-mlir#77]
Hello. Is there a way to run TPU-MLIR outside of a Docker container?

I do not need to generate a bmodel, I just want to use dialects to test conversion and inference.

What things need to be installed outside of Docker?

**Comment by HarmonyHu** [comment]
> Hello. Is there a way to run TPU-MLIR outside of a Docker container?
> 
> I do not need to generate a bmodel, I just want to use dialects to test conversion and inference.
> 
> What things need to be installed outside of Docker?

Sorry, we suggest to run in the docker, as the environment is complex.
