### ISSUE TITLE
./run_model.sh: line 34: /chip.cfg: No such file or directory

### ISSUE THREAD

**Issue by jo-dean** [sophgo/tpu-mlir#78]
跑第一次的时候是正常输出的，然后退出了容器，重新进行
运行`./run_model.sh yolov5s`
就出现了问题
![image](https://user-images.githubusercontent.com/38728358/218966874-22c5a19a-0368-42e5-824b-37f22703fba3.png)

**Comment by HarmonyHu** [comment]
需要先编译，source ./envsetup.sh, ./build.sh, 然后跑模型

**Comment by jo-dean** [comment]
已经解决了，每次进入容器需要重新编译

**Comment by HarmonyHu** [comment]
> 已经解决了，每次进入容器需要重新编译

不需要重新编译，但是要source ./envsetup.sh

**Comment by jo-dean** [comment]
ok
