### ISSUE TITLE
关于内存分配

### ISSUE THREAD

**Issue by ColdCodeCool** [sophgo/tpu-mlir#8]
感谢各位作者，这是目前我看到的第一个MLIR在ASIC工具链设计的应用，有非常高的指导价值！
在内存分配部分，看起来你们的芯片是采用了单级缓存吗，拥有一个超大SRAM？

**Comment by HarmonyHu** [comment]
SRAM比较小，用的多级缓存

**Comment by ColdCodeCool** [comment]
@HarmonyHu  抱歉，请问global memory是指DDR吗，local memory是指SRAM吗，请问你们的local memory有没有分层？
