### ISSUE TITLE
onnx_inference 推理onnx模型报错

### ISSUE THREAD

**Issue by wfs2010** [sophgo/tpu-mlir#87]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/33648603/221339997-4620ae26-a6ce-4386-a3c7-08d06e4eed28.png">

**Comment by wfs2010** [comment]
当我使用onnx_inference推理onnx模型时发生上述错误
具体的模型有
https://github.com/sophgo/model-zoo/vision/classification/efficientnetv2/efficientnetv2.onnx 
https://github.com/sophgo/model-zoo/blob/main/vision/classification/EfficientNet-B0/efficientnet-b0.onnx
https://github.com/sophgo/model-zoo/blob/main/vision/classification/vgg16/vgg16-12.onnx

**Comment by Silence-Zhang-beijng** [comment]
你是否按照https://github.com/sophgo/model-zoo#usage---git-lfs步骤下载模型？在clone model-zoo后，需要将使用的模型进行下载，然后才可以运行onnx_inference。
