### ISSUE TITLE
我pull了最新DIGEST：676f4ebcb792的docker镜像, 用3月1日的代码报错

### ISSUE THREAD

**Issue by wangxu372848892** [sophgo/tpu-mlir#90]
cd tpu-mlir
source ./envsetup.sh
./build.sh
途中会报错cmake  incomplete

**Comment by Silence-Zhang-beijng** [comment]
是否在docker中运行？有报错截图吗？

**Comment by wangxu372848892** [comment]
![image](https://user-images.githubusercontent.com/59901551/222372167-fc0d7330-0d49-4712-a1a5-bb1a3020e3a1.png)
docker 环境中，和我的系统版本没有关系是吧

**Comment by Silence-Zhang-beijng** [comment]
生成so文件需要使用git的commit信息。建议直接使用git clone https://github.com/sophgo/tpu-mlir.git来下载代码。直接使用zip会导致没有git信息，build失败

**Comment by OrdinaryChen** [comment]
> 生成so文件需要使用git的commit信息。建议直接使用git clone https://github.com/sophgo/tpu-mlir.git 来下载代码。直接使用zip会导致没有git信息，build失败

大神正解!
