### ISSUE TITLE
<unknown>:0: error: invalid tensor dimension size

### ISSUE THREAD

**Issue by Learnmore666** [sophgo/tpu-mlir#94]
当我跟随官网教程执行模型转换（onnx-->yolov5s.mlir）即运行model_transform.py时（官方全部参数未发生改动），遇到了一些问题，我有时能成功运行，但有时难以通过运行比如通过vscode对model_transform.py文件进行单步调试时，此时发现已经成功生成yolov5s_origin.mlir文件，以下是我的错误代码（error：invalid tensor dimension size）：
`Save mlir file: yolov5s_origin.mlir
[Running]: tpuc-opt --init --shape-infer --canonicalize --post-handle="type=yolo" --mark-FLOPs --save-weight --mlir-print-debuginfo yolov5s_origin.mlir -o yolov5s.mlir 
<unknown>:0: error: invalid tensor dimension size”
tpuc-opt: /workspace/third-party/llvm-project/mlir/include/mlir/IR/StorageUniquerSupport.h:153: static ConcreteT mlir::detail::StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits>::get(mlir::MLIRContext*, Args ...) [with Args = {llvm::ArrayRef<long int>, mlir::Type, mlir::Attribute}; ConcreteT = mlir::RankedTensorType; BaseT = mlir::TensorType; StorageT = mlir::detail::RankedTensorTypeStorage; UniquerT = mlir::detail::TypeUniquer; Traits = {mlir::SubElementTypeInterface::Trait, mlir::ShapedType::Trait}]: Assertion succeeded(ConcreteT::verify(getDefaultDiagnosticEmitFn(ctx), args...))' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
` 
`
”0.      Program arguments: tpuc-opt --init --shape-infer --canonicalize --post-handle=type=yolo --mark-FLOPs --save-weight --mlir-print-debuginfo yolov5s_origin.mlir -o yolov5s.mlir
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  tpuc-opt        0x000055cf9335550a
1  tpuc-opt        0x000055cf9335295c
2  libpthread.so.0 0x00007fd74b5b2980
3  libc.so.6       0x00007fd74a67fe87 gsignal + 199
4  libc.so.6       0x00007fd74a6817f1 abort + 321
5  libc.so.6       0x00007fd74a6713fa
6  libc.so.6       0x00007fd74a671472
7  tpuc-opt        0x000055cf932720f7
8  tpuc-opt        0x000055cf93272246
9  tpuc-opt        0x000055cf9306e78b
10 tpuc-opt        0x000055cf93118839
11 tpuc-opt        0x000055cf93119a08
12 tpuc-opt        0x000055cf92a82c0b
13 tpuc-opt        0x000055cf92a834bb
14 tpuc-opt        0x000055cf92a838f2
15 tpuc-opt        0x000055cf932dc36f
16 tpuc-opt        0x000055cf92a81384
17 tpuc-opt        0x000055cf92a83e6f
18 tpuc-opt        0x000055cf92a77ab1
19 libc.so.6       0x00007fd74a662c87 __libc_start_main + 231
20 tpuc-opt        0x000055cf92a804ba
Aborted
Traceback (most recent call last):
  File "/workspace/tpu-mlir/python/tools/model_transform.py", line 226, in <module>
    tool.model_transform(args.mlir, args.post_handle_type)
  File "/workspace/tpu-mlir/python/tools/model_transform.py", line 39, in model_transform
    mlir_opt_for_top(mlir_origin, self.mlir_file, post_handle_type)
  File "/workspace/tpu-mlir/python/utils/mlir_shell.py", line 29, in mlir_opt_for_top
    _os_system(cmd)
  File "/workspace/tpu-mlir/python/utils/mlir_shell.py", line 20, in _os_system
    raise RuntimeError("[!Error]: {}".format(cmd_str))
RuntimeError: [!Error]: tpuc-opt --init --shape-infer --canonicalize --post-handle="type=yolo" --mark-FLOPs --save-weight --mlir-print-debuginfo yolov5s_origin.mlir -o yolov5s.mlir” `
`
我根据提示单独使用tpuc-opt工具对 yolov5s_origin.mlir文件进行了pass优化，即执行了tpuc-opt --init --shape-infer --canonicalize --post-handle="type=yolo" --mark-FLOPs --save-weight --mlir-print-debuginfo yolov5s_origin.mlir -o yolov5s.mlir获得了相同的BUG信息。
通过对pass进行隔离调试发现主要因为pass选项:‘’--shape-infer‘’导致错误的发生，是否因为当前算子的shape_inference部分未完成导致？但我曾经尝试成功运行过该程序，目前暂不能通过gdb定位，因为根据官方流程tpuc-opt工具并未使用debug版本进行编译：
(gdb) file /workspace/tpu-mlir/install/bin/tpuc-opt
Reading symbols from /workspace/tpu-mlir/install/bin/tpuc-opt...(no debugging symbols found)..done
希望能得到回复，如果不能解决，我尝试重新部署docker容器。

**Comment by Silence-Zhang-beijng** [comment]
最近shape_inference改动较大。你更新代码再试一下。 GDB的问题，你可以执行./build.sh DEBUG来生成debug版本tpuc-opt。这样就可以用gdb定位问题了。以后问题可以在https://ask.tpumlir.org/questions提问。那里回复会更快
