### ISSUE TITLE
./build.sh throws error Deconv.cpp.o 

### ISSUE THREAD

**Issue by thunder95** [sophgo/tpu-mlir#95]
FAILED: lib/Conversion/TopToTpu/CMakeFiles/obj.TPUMLIRTopToTpu.dir/BM1684X/Deconv.cpp.o 
/usr/bin/c++ -DMLIR_VERSION=\"v0.9.beta.0-20230321\" -I../third_party/llvm/include -I../include -Iinclude -I../install/include -I../third_party/oneDNN/include -I../third_party/cnpy -I../third_party/flatbuffers/include -I../third_party/nntoolchain/include -I../third_party/CV18xx/include -I../third_party/progressbar/include -O2 -fopenmp -fPIC -Werror -Wno-unused-result -Wreturn-type -Wunused-variable -std=gnu++1z -MD -MT lib/Conversion/TopToTpu/CMakeFiles/obj.TPUMLIRTopToTpu.dir/BM1684X/Deconv.cpp.o -MF lib/Conversion/TopToTpu/CMakeFiles/obj.TPUMLIRTopToTpu.dir/BM1684X/Deconv.cpp.o.d -o lib/Conversion/TopToTpu/CMakeFiles/obj.TPUMLIRTopToTpu.dir/BM1684X/Deconv.cpp.o -c ../lib/Conversion/TopToTpu/BM1684X/Deconv.cpp
In file included from /usr/include/c++/7/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/7/memory:81,
                 from ../third_party/llvm/include/llvm/ADT/SmallVector.h:28,
                 from ../third_party/llvm/include/llvm/ADT/ArrayRef.h:13,
                 from ../third_party/llvm/include/llvm/ADT/STLExtras.h:20,
                 from ../third_party/llvm/include/llvm/ADT/TypeSwitch.h:18,
                 from ../include/tpu_mlir/Dialect/Top/IR/TopOps.h:12,
                 from ../include/tpu_mlir/Conversion/TopToTpu/TopLowering.h:12,
                 from ../include/tpu_mlir/Conversion/TopToTpu/LoweringBM1684X.h:12,
                 from ../lib/Conversion/TopToTpu/BM1684X/Deconv.cpp:10:
/usr/include/c++/7/bits/shared_ptr_base.h: In instantiation of ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Yp*, _Deleter) [with _Yp = dnnl_primitive_desc; _Deleter = dnnl_status_t (*)(dnnl_primitive_desc*); <template-parameter-2-3> = void; _Tp = dnnl_primitive_desc; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2]’:
/usr/include/c++/7/bits/shared_ptr_base.h:1249:4:   required from ‘std::__shared_ptr<_Tp, _Lp>::_SafeConv<_Yp> std::__shared_ptr<_Tp, _Lp>::reset(_Yp*, _Deleter) [with _Yp = dnnl_primitive_desc; _Deleter = dnnl_status_t (*)(dnnl_primitive_desc*); _Tp = dnnl_primitive_desc; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2; std::__shared_ptr<_Tp, _Lp>::_SafeConv<_Yp> = void]’
../third_party/oneDNN/include/oneapi/dnnl/dnnl.hpp:177:9:   required from ‘void dnnl::handle<T, traits>::reset(T, bool) [with T = dnnl_primitive_desc*; traits = dnnl::handle_traits<dnnl_primitive_desc*>]’
../third_party/oneDNN/include/oneapi/dnnl/dnnl.hpp:4062:21:   required from here
/usr/include/c++/7/bits/shared_ptr_base.h:1093:2: internal compiler error: Segmentation fault
  }
  ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
[643/864] Building CXX object lib/Conversion/TopToTpu/CMakeFiles/obj.TPUMLIRTopToTpu.dir/BM1684X/Exp.cpp.o
ninja: build stopped: subcommand failed.

**Comment by charlesxzb** [comment]
Please make sure you are using the updated docker image. Then update the code, it should work.

**Comment by OrdinaryChen** [comment]
> Please make sure you are using the updated docker image. Then update the code, it should work.
I use mater branch in docker sophgo/tpuc_dev:latest and   sophgo/tpuc_dev:v3.2-base-20240531, but failed neither.
[1012/1422] Linking CXX shared module lib/pyruntime_bm.cpython-310-x86_64-linux-gnu.so
FAILED: lib/pyruntime_bm.cpython-310-x86_64-linux-gnu.so
: && /usr/bin/ccache /usr/bin/clang++ -fPIC -O2 -fopenmp=libomp -fPIC -Werror -Wno-unused-result -Wreturn-type -Wunused-variable  -fuse-ld=lld -shared  -o lib/pyruntime_bm.cpython-310-x86_64-linux-gnu.so bindings/pyruntime/CMakeFiles/pyruntime_bm.dir/pyruntime_bm.cpp.o -L/workspace/CYZ/suanneng/tpu-mlir/third_party/nntoolchain/lib   -L/workspace/CYZ/suanneng/tpu-mlir/third_party/CV18xx/lib   -L/workspace/CYZ/suanneng/tpu-mlir/third_party/or-tools/lib -Wl,-rpath,"\${ORIGIN}/"  -lbmrt  -lcpuop && cd /workspace/CYZ/suanneng/tpu-mlir/build/bindings/pyruntime && /usr/local/bin/llvm-strip /workspace/CYZ/suanneng/tpu-mlir/build/lib/pyruntime_bm.cpython-310-x86_64-linux-gnu.so
ld.lld: error: /workspace/CYZ/suanneng/tpu-mlir/third_party/nntoolchain/lib/libbmrt.so:1: unexpected EOF
>>> libbmrt.so.1.0
>>> ^
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1035/1422] Building CXX object lib/Dialect/Tpu/CMakeFiles/TPUMLIRTpu.dir/IR/TpuOps.cpp.o
ninja: build stopped: subcommand failed.
